name: action

on:
  push:
    branches:
      - master

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
      - name: récupération du répertoire
        uses: actions/checkout@v3
      - name: mise en place de java & maven
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: vérification de la version de maven
        run: mvn -v
      - name: mise en place de docker
        uses: docker/setup-buildx-action@v3.0.0
      - name: vérification de la version de docker
        run: docker version
      - name: paquetage du projet
        run: mvn package -Dpackaging=docker -Dmicronaut.aot.enabled=true
      - name: affichage des images générées
        run: docker images
